version: "3"
services:
  sportsdata:
    image: sportsdata
    ports:
      - 8080:8080
    networks:
      - sport-solr
    depends_on:
      - solrsearch

  solrsearch:
    image: solr:6.6.6
    networks:
      - sport-solr
    ports:
      - 8983:8983
    entrypoint:
      - bash
      - "-c"
      - "precreate-core sport-Data; exec solr -f"
      - "cp schema.xml /var/solr/data/sport-Data/config/schema.xml"

networks:
  sport-solr: